### ISSUE TITLE
I'm feeling lucky feature

### ISSUE THREAD

**Issue by MephestoKhaan** [gausie/slack-frinkiac#2]
Hi! I love your bot! But sometimes is frustrating not getting the right quote.
Will it be possible to add a parameter so it returns the first match instead of a random one?

something like /frinkiac --lucky pi is exactly three

and in code:
    .then(results => results.data[0]) 
instead of the current randomization.

I am not sure about how to deploy this custom code into my slack but if I manage it, will you accept pull requests?

**Comment by gausie** [comment]
I'll try to do this when I have time!

**Comment by MephestoKhaan** [comment]
After using it for another 2 weeks in my company we just feel like maybe giving the first option as the default could even better (at least for us!)  and randomize with a command instead.

**Comment by gausie** [comment]
Seems sensible and I will do it when I get the time. Hopefully that's soon,
but PRs always welcome!
